from datetime import datetime
t = datetime.today()
print("Haftanin gununu kisaltir")
print(datetime.strftime(t,"%a"))
print("Haftanin gununu verir")
print(datetime.strftime(t,"%A"))
print("Ayin gununu kisaltir")
print(datetime.strftime(t,"%b"))
print("Ayin tamamini verir")
print(datetime.strftime(t,"%B"))
print("tarih saat ve zamani gosterir")
print(datetime.strftime(t,"%c"))
print("Gunu sayi olarak verir")
print(datetime.strftime(t,"%d"))
print("Yilin kacinci gunu oldugunu gosterir")
print(datetime.strftime(t,"%j"))
print("Ayi sayi olarak verir")
print(datetime.strftime(t,"%m"))
print("Yilin kacinci ayi oldugunu gosterir")
print(datetime.strftime(t,"%u"))
print("Yil degerinin son 2 rakamini gosterir")
print(datetime.strftime(t,"%y"))
print("Yilin tamamini verir")
print(datetime.strftime(t,"%Y"))
print("Tarih bilgisini verir")
print(datetime.strftime(t,"%x"))
print("Saat bilgisini verir")
print(datetime.strftime(t,"%X"))

