import math
print("Ondalik sayiyi en yakin sayiya yuvarlar")
print(math.ceil(1.1))
print("ikinci sayinini isaretini birinci sayiya verer")
print(math.copysign(-2,3))
print("mutlak degere alir")
print(math.fabs(-3))
print("faktoriyel alir")
print(math.factorial(4))
print("Ondalikli sayiyi en yakin alt tam sayiya yuvarlar")
print(math.floor(-1.1))
print("mod alir")
print(math.fmod(10,2))
print("Bunu anlamadim kullanmam")
print(math.frexp(5))
print("toplam buluculari")
print(math.fsum([.1,.1,.1,.1,.1,.1]))
print("Ebob")
print(math.gcd(12,24))
print("yakinlik bulucu")
print(math.isclose(15,20))
print("Kesirli kisim ve tam kisim ayirir")
print(math.modf(3.10))
print("integere donusturme")
print(math.trunc(1.7))
print("pi sayisi")
print(math.pi)
print("euler sayisi")
print(math.e)
print("tau sayisi")
print(math.tau)
print("euler sabit us alma")
print(math.exp(2))
print("ustteki komutun sonucundan 1 cikarir")
print(math.expm1(2))
print("logaritma")
print(math.log(1,10))
print("1+x(taban e)")
print(math.log1p(1))
print("2 tabanina gore logaritma")
print(math.log2(8))
print("10 tabanina gore logaritma")
print(math.log10(100))
print("kuvvet alma")
print(math.pow(2,3))
print("karekok")
print(math.sqrt(9))
