import math
print("radyan -> derece")
print(math.degrees(45))
print("derece -> radyan")
print(math.radians(300))
print("arccos")
print(math.acos(1))
print("arcsin")
print(math.asin(10))
print("arctan")
print(math.atan(0))
print(math.atan2(12,3))
print("cos")
print(math.cos(0))
print("x*x + y*y")
print(math.hypot(1,2))
print("sin")
print(math.sin(90))
print("ters hiperbolik cos")
print(math.acosh(0))
print("ters hiperbolik sin")
print(math.asinh(90))
print("ters hiperbolik tan")
print(math.atanh(10))
print("hiperbolik cos")
print(math.cosh(100))
print("hiperbolik sin")
print(math.sinh(110))
print("hiperbolik tan")
print(math.tanh(12))
print("1 eksiginin faktoriyeli")
print(math.gamma(2))
print("gamma hesaplayip logaritma yapar")
print(math.lgamma(5))
